# Generated by Django 4.1.4 on 2022-12-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=255, unique_for_month='data', verbose_name='descricao'),
        ),
    ]
