# Generated by Django 4.1.4 on 2022-12-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_alter_despesa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(default='Outras', max_length=15),
        ),
    ]
