# Generated by Django 4.1.4 on 2022-12-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_despesa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('Alimentação', 'Alimentacao'), ('Saúde', 'Saude'), ('Moradia', 'Moradia'), ('Transporte', 'Transporte'), ('Educação', 'Educacao'), ('Lazer', 'Lazer'), ('Imprevistos', 'Imprevistos'), ('Outras', 'Outras')], default='Outras', max_length=15),
        ),
    ]
